[phases.setup]
nixPkgs = ["python3", "pip"]

[phases.install]
cmds = ["pip install -r requirements/prod.txt"]

[phases.build]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install -r requirements/prod.txt"
]

[start]
cmd = "python main.py" 