[phases.setup]
nixPkgs = ["nodejs", "yarn"]

[phases.install]
cmds = ["cd server && yarn install --frozen-lockfile"]

[phases.build]
cmds = ["cd server && yarn build"]

[start]
cmd = "cd server && yarn serve"
