[phases.setup]
nixPkgs = ["nodejs", "yarn"]

[phases.install]
cmds = ["cd server && yarn install --frozen-lockfile"]

[phases.build]
cmds = [
    "cd server && yarn build",
    "cd server && chmod +x setup-env.sh",
    "cd server && ./setup-env.sh"
]

[start]
cmd = "cd server && yarn start"
