[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "nodejs-api"
sourceDir = "server"
healthcheckPath = "/api/v1/health"

[[services]]
name = "python-ml"
sourceDir = "python-ml-service"
healthcheckPath = "/api/v1/health"