export const EXCHANGES: string[] = [
  'NYSE',
  'NASDAQ',
  'LSE (London Stock Exchange)',
  'JPX (Tokyo Stock Exchange)',
  'HKEX (Hong Kong Stock Exchange)',
  'Euronext',
  'SSE (Shanghai Stock Exchange)',
  'SZSE (Shenzhen Stock Exchange)',
  'SIX Swiss Exchange',
  'ASX (Australian Securities Exchange)',
  'TSX (Toronto Stock Exchange)',
  'BSE (Bombay Stock Exchange)',
  'NSE (National Stock Exchange of India)',
  'Deutsche Börse (Xetra)',
  'B3 (Brasil Bolsa Balcão)',
  'JSE (Johannesburg Stock Exchange)',
  'SGX (Singapore Exchange)',
  'KRX (Korea Exchange)',
  'BME (Bolsa de Madrid)',
  'Borsa Italiana',
  'TASE (Tel Aviv Stock Exchange)',
  'MOEX (Moscow Exchange)',
  'WSE (Warsaw Stock Exchange)',
  'VSE (Vienna Stock Exchange)',
  'OSE (Oslo Stock Exchange)',
  'OMX Stockholm',
  'OMX Helsinki',
  'OMX Copenhagen',
  'OMX Iceland',
  'Bucharest Stock Exchange',
  'Athens Stock Exchange (ATHEX)',
  'ISE (Irish Stock Exchange/Euronext Dublin)',
  'Luxembourg Stock Exchange',
  'Prague Stock Exchange (PSE)',
  'Budapest Stock Exchange (BSE Hungary)',
  'Santiago Stock Exchange (BCS)',
  'BM&F (Brazil Derivatives)',
  'Bolsa Mexicana de Valores (BMV)',
  'Bolsa de Valores de Colombia (BVC)',
  'Peru Stock Exchange (BVL Lima)',
  'Bursa Malaysia',
  'Taiwan Stock Exchange (TWSE)',
  'Thailand Stock Exchange (SET)',
  'Philippine Stock Exchange (PSE)',
  'Indonesia Stock Exchange (IDX)',
  'New Zealand Exchange (NZX)',
  'Saudi Exchange (Tadawul)',
  'Abu Dhabi Securities Exchange (ADX)',
  'Dubai Financial Market (DFM)',
  'Qatar Stock Exchange (QSE)',
  'Kuwait Stock Exchange (Boursa Kuwait)',
  'Bahrain Bourse',
  'Muscat Stock Exchange (MSX)',
  'Pakistan Stock Exchange (PSX)',
  'Colombo Stock Exchange (CSE Sri Lanka)',
  'Ho Chi Minh Stock Exchange (HOSE)',
  'Hanoi Stock Exchange (HNX)',
  'Johannesburg AltX',
  'Nairobi Securities Exchange (NSE Kenya)',
  'Egyptian Exchange (EGX)',
  'Casablanca Stock Exchange (CSE Morocco)'
];


