// Top 50 industries covering major sectors
export const INDUSTRIES = [
  'Technology',
  'Healthcare',
  'Finance',
  'Education',
  'Manufacturing',
  'Retail',
  'Real Estate',
  'Transportation',
  'Energy',
  'Media & Entertainment',
  'Consulting',
  'Legal',
  'Insurance',
  'Telecommunications',
  'Aerospace & Defense',
  'Automotive',
  'Food & Beverage',
  'Pharmaceuticals',
  'Construction',
  'Hospitality & Tourism',
  'Non-profit',
  'Government',
  'Agriculture',
  'Mining',
  'Banking',
  'Investment Management',
  'Accounting',
  'Marketing & Advertising',
  'Human Resources',
  'Logistics & Supply Chain',
  'Biotechnology',
  'Chemical',
  'Electronics',
  'Textiles & Apparel',
  'Utilities',
  'Oil & Gas',
  'Renewable Energy',
  'Environmental Services',
  'Security',
  'Software Development',
  'E-commerce',
  'Fitness & Wellness',
  'Publishing',
  'Broadcasting',
  'Gaming',
  'Architecture & Design',
  'Engineering',
  'Research & Development',
  'Veterinary Services',
  'Other'
] as const;

export type Industry = typeof INDUSTRIES[number];
